language: rust
rust:
  - nightly
script:
  - ./build.sh
cache: cargo

deploy:
  provider: pages
  local-dir: target/deploy
  skip-cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  on:
    branch: master
